#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www and display information about subdomains

check_record () {
	Ans=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:')
	record=$(echo $Ans | awk '{print $7}')
	IP=$(echo $Ans | awk '{print $8}')
	echo "The subdomain $2 is a $record record and points to $IP"
}
if [ $# -eq 1 ]
then
	check_record "$1" "www"
	check_record "$1" "lb-01"
	check_record "$1" "web-01"
	check_record "$1" "web-02"
else
	check_record "$1" "$2"
fi
