#!/usr/bin/env bash
# configure my nginx server
# /redirect_me is redirectiong me to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.html
sudo sed -i '45a \\trewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
