#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 75017-web-01 54.160.71.218:80 check\n\tserver 75017-web-02 54.146.75.210:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
